name: Update Metadata on Release

on:
  release:
    types: [published]

concurrency: update_metadata

permissions:
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          ref: master

      - name: "Update metadata"
        run: |
          sed "/versions:/a\  - sha: $(git rev-parse HEAD)\n    changeNotes: ${{ github.event.release.name }}\n" metadata.yaml > metadata_tmp.yaml
          cat metadata_tmp.yaml > metadata.yaml
          rm metadata_tmp.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch chore/update-metadata
          git add .
          git commit -m "Update Metadata"
          gh pr create -B master -H chore/update-metadata --title 'Update Metadata' --body ''
